[package]
name = "tui_basketball"
version = "0.1.0"
edition = "2024"
description = "Terminal based NBA game stats viewer using ratatui"
readme = "README.md"
keywords = ["NBA", "terminal"]
license = "MIT"
repository = "https://github.com/Shaven-Wickramanayaka/tui_basketball"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.29.0"
ratatui = "0.30.0"
reqwest = { version = "0.12", features = ["json", "blocking"] }
serde = { version = "1", features = ["derive"] }
chrono = "0.4" 
serde_json = "1.0.48"

# Read the optimization guideline for more details: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true